swagger: '2.0'
info:
  description: Scalol REST API specification
  version: 1.0.0
  title: Scalol
tags:
  - name: pet
    description: Everything about your daily dose of fun
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: store
    description: Scalol operations
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: 'http://swagger.io'
schemes:
  - http
paths:

  /posts:
    get:
      tags:
        - posts
      summary: Returns last posts. Without query parameters it will return only the last 100 posts
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: offset
          in: query
          description: >-
            The current id from where you want to read.
          required: false
        - name: number
          in: query
          description: >-
            The number of post you want to retrive.
          required: false
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Post'
    post:
      tags:
        - posts
      summary: Create a new post
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: token
          description: token to be passed as a header (header's name must be "auth")
          required: true
          type: string
        - name: body
          in: body
          description: 'New post data'
          required: true
          schema:
            type: object
            properties:
              title:
                type: string
              image_path:
                type: string
              nsfw:
                type: boolean
      responses:
        '200':
          description: Post submitted
          schema:
            type: object
            properties:
              location:
                type: string
              owner:
                type: string
        '400':
          description: Missing auth | an other cause
          schema:
            type: object
            properties:
              cause:
                type: string
        '403':
          description: Invalid auth.


  /posts/{post_id}:
    get:
      tags:
        - posts
      summary: Returns a post
      produces:
        - application/json
      parameters:
      - name: post_id
        in: path
        description: The post that needs to be fetched.
        required: true
        type: int64
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              post:
                $ref: '#/definitions/Post'
        '404':
          description: post not found

  /auth:
    post:
      tags:
        - Auth
      summary: Logs user into the system
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: The user credentials
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: Json containing auth token
          schema:
            type: object
            properties:
              token:
                type: string
        '400':
          description: Bad request
          schema:
            type: object
            properties:
              cause:
                type: string
        '403':
          description: Invalid usernamer and/or password
  '/user':
    post:
      tags:
        - user
      summary: Creates a new user.
      description: ''
      produces:
        - application/json
      parameters:
      - name: body
        in: body
        description: user object
        required: true
        schema:
          type: object
          properties:
            username:
              type: string
            email:
              type: string
            password:
              type: string
      responses:
        '200':
          description: Json containing auth token
          schema:
            type: object
            properties:
              token:
                type: string
        '400':
          description: Bad request
          schema:
            type: object
            properties:
              cause:
                type: string
        '409':
          description: Username already taken
    patch:
      tags:
        - user
      summary: Update user
      produces:
        - application/json
      parameters:
        - in: header
          name: token
          description: token to be passed as a header (header's name must be "auth")
          required: true
          type: string
        - in: body
          name: body
          description: Updated user object
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              mail:
                type: string
              password:
                type: string
      responses:
        '200':
          description: Ok
        '400':
          description: Bad request
          schema:
            type: object
            properties:
              cause:
                type: string
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      produces:
        - application/json
      parameters:
        - in: header
          name: token
          description: token to be passed as a header (header's name must be "auth")
          required: true
          type: string
      responses:
        '200':
          description: Ok
        '403':
          description: forbidden
          schema:
            type: object
            properties:
              cause:
                type: string
  '/user/{username}':
    get:
      tags:
        - user
      summary: Get user's information and posts by user name
      description: ''
      produces:
        - application/json
      parameters:
        - name: username
          in: path
          description: The username that needs to be fetched.
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              userView:
                $ref: '#/definitions/UserView'
              posts:
                type: array
                items:
                  $ref: '#/definitions/Post'
        '404':
          description: User not found
          schema:
            type: object
            properties:
              cause:
                type: string
  /comments:
    post:
      tags:
        - comments
      summary: Post a new comment
      consumes:
        - application/json
      parameters:
        - in: header
          name: token
          description: token to be passed as a header (header's name must be "auth")
          required: true
          type: string
        - name: body
          in: body
          description: Comment data
          required: true
          schema:
            $ref: '#/definitions/Comment'
      responses:
        '200':
          description: Comment submitted
  '/comments/{postId}':
    get:
      tags:
        - comments
      produces:
        - application/json
      parameters:
        - name: postId
          in: path
          required: true
          type: integer
          format: int64
          description: Post whose comments need to be fetched
      responses:
        '200':
          description: Operation successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Comment'
  /messages/{to_username}:
    post:
      tags:
        - message
      summary: Send a new message
      consumes:
        - application/json
      parameters:
        - in: header
          name: token
          description: token to be passed as a header (header's name must be "auth")
          required: true
          type: string
        - name: to_username
          in: path
          required: true
          type: string
          description: User that will recive the message
        - name: body
          in: body
          description: Message data
          required: true
          schema:
            $ref: '#/definitions/MessageTo'
      responses:
        '200':
          description: Message sent.
        '400':
          description: Invalid body | missing auth.
        '403':
          description: The user has blocked you | invalid auth.
        '404':
          description: The user does not exists.

    get:
      tags:
        - message
      produces:
        - application/json
      parameters:
        - in: header
          name: token
          description: token to be passed as a header (header's name must be "auth")
          required: true
          type: string
        - name: to_username
          in: path
          required: true
          type: string
          description: the target user to load the messages
      responses:
        '200':
          description: Operation successful
          schema:
            type: array
            items:
              $ref: '#/definitions/MessageFrom'

        '400':
          description: Missing auth.
        '403':
          description: Invalid auth.
        '404':
          description: The requested user does not exist.
  /messages:
    get:
        tags:
          - message
        summary: Returns a list of conversation
        produces:
          - application/json
        parameters:
          - in: header
            name: token
            description: token to be passed as a header (header's name must be "auth")
            required: true
            type: string
        responses:
          '200':
            description: Operation successful
            schema:
              type: array
              items:
                $ref: '#/definitions/MessageBox'

          '400':
            description: Missing auth | other reason.
          '403':
            description: Invalid auth.

  /block_user/{username}:
    get:
        tags:
          - message
        summary: blocks the user
        parameters:
          - in: header
            name: token
            description: token to be passed as a header (header's name must be "auth")
            required: true
            type: string
          - name: username
            in: path
            required: true
            type: string
            description: the user to block
        responses:
          '200':
            description: Operation successful
          '400':
            description: Missing auth.
          '403':
            description: Invalid auth.
          '404':
            description: Not found.

  /unblock_user/{username}:
    get:
        tags:
          - message
        summary: unblocks the user
        parameters:
          - in: header
            name: token
            description: token to be passed as a header (header's name must be "auth")
            required: true
            type: string
          - name: username
            in: path
            required: true
            type: string
            description: the user to unblock
        responses:
          '200':
            description: Operation successful
          '400':
            description: Missing auth.
          '403':
            description: Invalid auth.
          '404':
            description: Not found.

  /mark_as_read/{username}:
    get:
        tags:
          - message
        summary: marks the conversation as read
        parameters:
          - in: header
            name: token
            description: token to be passed as a header (header's name must be "auth")
            required: true
            type: string
          - name: username
            in: path
            required: true
            type: string
            description: the user with with you had a conversation
        responses:
          '200':
            description: Operation successful
          '400':
            description: Missing auth.
          '403':
            description: Invalid auth.
          '404':
            description: Not found.

  /upvote/{post_id}:
    put:
      tags:
        - posts
      parameters:
        - in: header
          name: token
          description: token to be passed as a header (header's name must be "auth")
          required: true
          type: string
        - in: path
          name: post_id
          description: The post to be upvoted.
          required: true
          type: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Missing auth
        '403':
          description: Invalid auth.
  /downvote/{post_id}:
    put:
      tags:
        - posts
      parameters:
        - in: header
          name: token
          description: token to be passed as a header (header's name must be "auth")
          required: true
          type: string
        - in: path
          name: post_id
          description: The post to be downvoted.
          required: true
          type: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Missing auth
        '403':
          description: Invalid auth.

  /upload:
    post:
      tags:
        - posts
      parameters:
        - in: header
          name: token
          description: token to be passed as a header (header's name must be "auth")
          required: true
          type: string
        - in: body
          name: body
          description: >-
           Just a regular file input in HTML should to the trick.
           The key is picture.
           See postman example on github repo.
          required: true
      responses:
        '200':
          description: Post submitted
          schema:
            type: object
            properties:
              location:
                type: string
        '400':
          description: Bad request
          schema:
            type: object
            properties:
              cause:
                type: string
definitions:
  Comment:
    type: object
    properties:
      post_id:
        type: integer
        format: int64
      username:
        type: string
      content:
        type: string
      id:
        type: integer
        format: int64
  MessageFrom:
    type: object
    properties:
      from:
        type: string
      content:
        type: string
      date:
        type: string
      viewed:
        type: boolean
      user_blocked:
        type: boolean
  MessageTo:
    type: object
    properties:
      content:
        type: string
  MessageBox:
    type: object
    properties:
      from:
        type: string
  Post:
    type: object
    properties:
      id:
        type: integer
        format: int64
      owner_id:
        type: integer
        format: int64
      score:
        type: integer
        format: int64
      title:
        type: string
      image_path:
        type: string
      nsfw:
        type: boolean
  UserView:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      mail:
         type: string
      rank:
        type: integer
        format: int64
      password:
        type: string